export const WATCHLIST_INITIALIZE = "WATCHLIST_INITIALIZE";
export const WATCHEDLIST_INITIALIZE = "WATCHEDLIST_INITIALIZE";
export const ADD_WATCHLIST = "ADD_WATCHLIST";
export const ADD_WATCHEDLIST = "ADD_WATCHEDLIST";
export const WATCHLIST_DELETE = "WATCHLIST_DELETE";
export const WATCHEDLIST_DELETE = "WATCHEDLIST_DELETE";
